name: Reflections on Freedom
favicon: null
layout_spectrum: 0.13089273287914693
typography_spectrum: 1
title: Reflections on Freedom
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#313131'
    - '#01b12e'
    - '#c3c3c3'
  brandStrength: 0.375
  lightness: 0.6888151888269931
  saturation: 0.6899626080412418
  rhythmicContrast: 0.7701998350676149
purpose: []
